services:
  php-8.3:
    image: php:8.3-alpine
    entrypoint: ['sh', 'entrypoint.sh']
    environment:
      XDEBUG_CONFIG: 'client_host=host.docker.internal'
      XDEBUG_MODE: 'coverage,debug'
    depends_on:
      mongodb:
        condition: service_started
    volumes:
        - ./:/var/www/event-storage-in-mongodb-with-php
    working_dir: /var/www/event-storage-in-mongodb-with-php

  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    environment:
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
